language: node_js
node_js:
  - 8.11.1
branches:
  only:
    - master
before_install:
  - npm install -g npm@6.4.1
install:
  - npm install -g @angular/cli@6.2.4
  - npm install -g firebase-tools@6.1.0
  - npm install
script:
  - ng build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "oelHojkv15vJbdljTsep6U8TM8kDrOjQpZ1MHddSb+ZM8qshqp4fpUr6I5/hxRilwnoeUC9S3/00GHSa9SlaCqgbUHN+KEW1XfEgBL54v9i1TUpR+M5c3TTc4PRCmqYt0cDrGAZ8iW/dWDvG+n+zJZxPS7Y5FWk+R41J8JWKAzRPcxAGNFOGPioCoyR1JlFUYf5DPRnT+DatG+oibJVtK51eo/QvqwxpJiLzKdkp8e+YcYtWpZlqoOYuwmaqGGQ2NLtAY8fjbT/T5tCxkA4TxYml3MxXKucn7A0vK286vagYHqwLgjYddqy9wEJnq2oIbB/8Ej3FSrL0VuTlsVNPMx6xMmiLNvPfP2oUsz1ItKiYZ3HooqrGiGiOpRjAVVh1zw7xqECvfRHJtdI9X7x0nUN+nqZAXqgzXtjN6SaxhgqBTay/Yl2TLVJUGHVEp2ERqrKpXhEWpMh0fyROsMBRV51QrUjM1YJ3UyJVLvCwNxkyqvBZ7uksXwNkQbXLP9qrkiaGPle3s2+ENRQwpMjfm/IKjK2KtMEYU82IUXMdulDrBA+rVru9yig+ZJROvdYS/+Q+SWds59M5MeXzXXNFKRYfO0Pwydt5at+xkeRlEOIUyVsHyASNQSvl/5g8dovSWy6Huj/AjeAqgOs9GKuwqkULMZ3yI1ZtedppHVBrhew="
  project: "stack-attack"
