language: node_js
node_js:
    - "8.11.1"
branches:
  only:
    - master
before_install:
    - npm install -g npm@6.4.1
install:
    - npm install -g @angular/cli@6.2.4
    - npm install -g firebase-tools@6.1.0
    - npm install
deploy:
  provider: firebase
  token:
    secure: "p0StlooS1Wo3hw+FiAersnfCdyUJiMjYRuIAH1ZdBrwq75ruDVqrjQxi6GUMupO0rQqeSht11hUqFm4bwNzHM1wKU6Yy3IieEWnpRrUSdixzn+XFQpaha0yAk180w8g7zVFj/RZMaW01nxJfjOzU/rHU1sIn7c/a45bAWmKO6vaGlsaIuJWHVpfsae8w1I0KnlKc2Vhs5aVCEQ11g74hZO1MJaV3tiUMBLoSmbhWMu01W8Fi6kzJy1CNuFvY76PK64wIYa/3QAkqDTbXbfi+mCa7+lIBpDwypwYAbpJHAbsBX+6OIelvZtKeHaoS0iLZrrCOcxH6M92cKQOoRAJVJ5ZfmyP7WixJkytlCXYUnEgKBRVR9utsXHDOX3JTi7LEFaYh2bqSU+6KQjpoMg5ixI/+ygbcw3dtkyKxvGwPguOcNKVaSw5b9y8wHmRTCspf/R/4mzQYpV5qhcKbFkPrxCBq5Q+rwCrfayCz/TvrkKg6VBSb57Jl1yCfkVk2ZHDb1ErAVy75lTU4VG0h85izmZOuaajpYfJeZdTE6M8XNB4k65apnFf5MWELtLG2763nR1Q0+1/UiBg42RIofVlGx6tB7954+H3w+IxTc7T1/Q2PemHPXPGbW19vyXWViThu7MZo8i5w4unTFcpWac8m4U32mdjPianGqqOupmdLguw="
